# Generated by Django 5.2.3 on 2025-06-23 16:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur Simple')], default='user', max_length=10)),
                ('matricule', models.CharField(help_text="Code unique d'identification du personnel", max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Le matricule doit contenir entre 3 et 20 caractères alphanumériques en majuscules', regex='^[A-Z0-9]{3,20}$')])),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir entre 8 et 15 chiffres et peut commencer par +', regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Désignez si cet utilisateur doit être traité comme actif. Décochez plutôt que de supprimer les comptes.', verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, help_text="Désigne si l'utilisateur peut se connecter au site d'administration.", verbose_name='Statut équipe')),
                ('is_superuser', models.BooleanField(default=False, help_text='Désigne que cet utilisateur a toutes les permissions sans les assigner explicitement.', verbose_name='Statut superutilisateur')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Tentatives de connexion échouées')),
                ('account_locked_until', models.DateTimeField(blank=True, null=True, verbose_name="Compte verrouillé jusqu'à")),
                ('password_change_required', models.BooleanField(default=False, verbose_name='Changement de mot de passe requis')),
                ('password_last_changed', models.DateTimeField(blank=True, null=True, verbose_name='Dernière modification du mot de passe')),
                ('notes', models.TextField(blank=True, help_text='Notes internes pour les administrateurs', verbose_name='Notes administratives')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_users', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'organisation")),
                ('monthly_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='En devise locale', max_digits=15, null=True, verbose_name="Chiffre d'affaires mensuel")),
                ('address', models.TextField(verbose_name='Adresse')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir entre 8 et 15 chiffres et peut commencer par +', regex='^\\+?1?\\d{8,15}$')], verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='Navigateur')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Heure de connexion')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Session active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session Utilisateur',
                'verbose_name_plural': 'Sessions Utilisateurs',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=20, unique=True, verbose_name='Identifiant unique')),
                ('first_name', models.CharField(max_length=200, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=200, verbose_name='Nom')),
                ('type_adherent', models.CharField(choices=[('physical', 'Personne Physique'), ('legal', 'Personne Morale')], max_length=20, verbose_name="Type d'adhérent")),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone1', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir entre 8 et 15 chiffres et peut commencer par +', regex='^\\+?1?\\d{8,15}$')], verbose_name='Téléphone principal')),
                ('phone2', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir entre 8 et 15 chiffres et peut commencer par +', regex='^\\+?1?\\d{8,15}$')], verbose_name='Téléphone secondaire')),
                ('join_date', models.DateField(verbose_name="Date d'adhésion")),
                ('activity_name', models.CharField(max_length=200, verbose_name="Nom de l'activité")),
                ('badge_validity', models.DateField(verbose_name='Validité du badge')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Photo de profil')),
                ('activity_image', models.ImageField(blank=True, null=True, upload_to='activity_images/', verbose_name="Image de l'activité")),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Code-barres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherents', to='core.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Adhérent',
                'verbose_name_plural': 'Adhérents',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['identifiant'], name='core_adhere_identif_38bc87_idx'), models.Index(fields=['badge_validity'], name='core_adhere_badge_v_0a92bf_idx'), models.Index(fields=['join_date'], name='core_adhere_join_da_f6d641_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('password_change', 'Changement de mot de passe'), ('password_reset', 'Réinitialisation de mot de passe'), ('account_locked', 'Compte verrouillé'), ('account_unlocked', 'Compte déverrouillé'), ('user_created', 'Utilisateur créé'), ('user_modified', 'Utilisateur modifié'), ('user_deactivated', 'Utilisateur désactivé'), ('user_activated', 'Utilisateur activé'), ('data_access', 'Accès aux données'), ('data_modification', 'Modification des données')], max_length=20, verbose_name='Action')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('success', models.BooleanField(default=True, verbose_name='Succès')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Journal des Actions',
                'verbose_name_plural': 'Journaux des Actions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_userac_user_id_9ccfb2_idx'), models.Index(fields=['action', 'timestamp'], name='core_userac_action_c8e369_idx')],
            },
        ),
    ]
