# Generated by Django 5.2.3 on 2025-06-24 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='identifiant',
            field=models.CharField(default='ORG0000001', max_length=10, unique=True, verbose_name="Identifiant de l'organisation"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('superviseur', 'Gestionnaire des adhérents'), ('agent', 'Agent de collecte')], default='agent', max_length=20),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=20, unique=True, verbose_name='Identifiant')),
                ('report', models.TextField(verbose_name='Rapport')),
                ('due_date', models.DateTimeField(verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='in_progress', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.adherent', verbose_name='Adhérent')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='Personnel')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifiant'], name='core_intera_identif_f86c33_idx'), models.Index(fields=['status'], name='core_intera_status_cecb73_idx'), models.Index(fields=['created_at'], name='core_intera_created_5254ce_idx')],
            },
        ),
    ]
