# Generated by Django 4.2.10 on 2025-06-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='activity_name',
            field=models.CharField(blank=True, help_text="Activité principale de l'adhérent", max_length=200, null=True, verbose_name="Nom de l'activité"),
        ),
        migrations.AddField(
            model_name='adherent',
            name='badge_validity',
            field=models.DateField(blank=True, help_text="Date de validité du badge d'adhérent", null=True, verbose_name='Validité du badge'),
        ),
    ]
