# Generated by Django 4.2.10 on 2025-06-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adherent_activity_name_adherent_badge_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom du template')),
                ('template_type', models.CharField(choices=[('classic', 'Classique'), ('modern', 'Moderne'), ('premium', 'Premium')], max_length=20, verbose_name='Type de template')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Badge',
                'verbose_name_plural': 'Templates de Badges',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='badge',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Design du badge', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.badgetemplate', verbose_name='Template de badge'),
        ),
    ]
