# Generated by Django 5.2.3 on 2025-07-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adherent_activity_name_adherent_badge_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userobjective',
            name='base_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Valeur de base'),
        ),
    ]
