# Generated by Django 4.2.23 on 2025-06-25 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_identifiant_alter_user_role_interaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de badge')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='badge_qr_codes/', verbose_name='QR Code')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('revoked', 'Révoqué')], default='active', max_length=20, verbose_name='Statut')),
                ('issued_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='core.adherent', verbose_name='Adhérent')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_badges', to=settings.AUTH_USER_MODEL, verbose_name='Émis par')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['-issued_date'],
                'indexes': [models.Index(fields=['badge_number'], name='core_badge_badge_n_98db59_idx'), models.Index(fields=['status'], name='core_badge_status_a8b912_idx'), models.Index(fields=['issued_date'], name='core_badge_issued__137889_idx')],
            },
        ),
    ]
