# Generated by Django 5.2.3 on 2025-07-04 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userobjective_base_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='auteur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
    ]
