# Generated by Django 5.2.3 on 2025-07-06 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fix_systemlog_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='num_urgence1',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 9 chiffres et doit commencer par un 6', regex='^(6)\\d{8}$')], verbose_name="Numéro d'urgence"),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='num_urgence2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 9 chiffres et doit commencer par un 6', regex='^(6)\\d{8}$')], verbose_name="Numéro d'urgence 2"),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='phone1',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 9 chiffres et doit commencer par un 6', regex='^(6)\\d{8}$')], verbose_name='Téléphone principal'),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 9 chiffres et doit commencer par un 6', regex='^(6)\\d{8}$')], verbose_name='Téléphone secondaire'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 9 chiffres et doit commencer par un 6', regex='^(6)\\d{8}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 9 chiffres et doit commencer par un 6', regex='^(6)\\d{8}$')], verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 9 chiffres et doit commencer par un 6', regex='^(6)\\d{8}$')]),
        ),
    ]
