# Generated by Django 5.2.3 on 2025-07-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_is_system_to_referencevalue'),
        ('core', '0007_alter_adherent_num_urgence1_and_more'),
    ]

    operations = [
    ]
