# Generated by Django 5.2.3 on 2025-07-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_interaction_identifiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='identifiant',
            field=models.IntegerField(editable=False, unique=True, verbose_name='Identifiant'),
        ),
    ]
