# Generated by Django 5.2.3 on 2025-07-14 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_adherent_num_urgence2_alter_adherent_phone2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='num_urgence1',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 9 chiffres et doit commencer par un 6', regex='^(6)\\d{8}$')], verbose_name="Numéro d'urgence"),
        ),
    ]
