# Generated by Django 5.2.3 on 2025-07-28 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_adherent_num_urgence1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.TextField(blank=True, help_text="Adresse complète de l'utilisateur", verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='user',
            name='nom_urg1',
            field=models.CharField(blank=True, max_length=100, verbose_name="Nom du contact d'urgence 1"),
        ),
        migrations.AddField(
            model_name='user',
            name='nom_urg2',
            field=models.CharField(blank=True, max_length=100, verbose_name="Nom du contact d'urgence 2"),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom_urg1',
            field=models.CharField(blank=True, max_length=100, verbose_name="Prénom du contact d'urgence 1"),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom_urg2',
            field=models.CharField(blank=True, max_length=100, verbose_name="Prénom du contact d'urgence 2"),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone_urg1',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 9 chiffres et doit commencer par un 6', regex='^(6)\\d{8}$')], verbose_name="Téléphone du contact d'urgence 1"),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone_urg2',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 9 chiffres et doit commencer par un 6', regex='^(6)\\d{8}$')], verbose_name="Téléphone du contact d'urgence 2"),
        ),
    ]
