# Generated by Django 4.2.7 on 2025-09-15 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_adresse_user_nom_urg1_user_nom_urg2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 9 chiffres et doit commencer par un 6', regex='^(6)\\d{8}$')], verbose_name='Téléphone'),
        ),
    ]
