# Generated by Django 5.2.3 on 2025-09-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_organization_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='hobies',
        ),
        migrations.AddField(
            model_name='adherent',
            name='hobies',
            field=models.TextField(blank=True, help_text="Hobbies ou centres d'intérêt de l'adhérent", verbose_name='Hobbies'),
        ),
    ]
