# Generated by Django 4.2.7 on 2025-09-17 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='hobies',
        ),
        migrations.AddField(
            model_name='adherent',
            name='centre_interet',
            field=models.ForeignKey(blank=True, help_text="Centre d'intérêt principal de l'adhérent", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adherents_centre_interet', to='core.referencevalue', verbose_name="Centre d'intérêt"),
        ),
        migrations.AlterField(
            model_name='referencevalue',
            name='category',
            field=models.CharField(choices=[('interaction_status', "Statuts d'interaction"), ('profession_types', 'Types de profession'), ('adherent_types', "Types d'adhérent"), ('organization_categories', "Catégories d'organisation"), ('badge_status', 'Statuts de badge'), ('objective_status', "Statuts d'objectif"), ('user_roles', 'Rôles utilisateur'), ('phone_types', 'Types de téléphone'), ('emergency_types', "Types d'urgence"), ('medical_info_types', "Types d'informations médicales"), ('formation_types', 'Types de formation'), ('distinction_types', 'Types de distinction'), ('language_types', 'Types de langue'), ('activity_types', "Types d'activité"), ('centres_d_interet', "Centres d'intérêt")], max_length=50, verbose_name='Catégorie'),
        ),
    ]
