# Generated by Django 4.2.7 on 2025-09-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_centre_interet_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adherent',
            name='centre_interet',
        ),
        migrations.AddField(
            model_name='adherent',
            name='centres_interet',
            field=models.ManyToManyField(blank=True, help_text="Centres d'intérêt de l'adhérent (sélection multiple possible)", related_name='adherents_centres_interet', to='core.referencevalue', verbose_name="Centres d'intérêt"),
        ),
    ]
