# Generated by Django 5.2.3 on 2025-09-19 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_multiple_centres_interet'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adherents', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
    ]
