# Generated by Django 5.2.3 on 2025-09-22 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_adherent_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions_created', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
    ]
