# Generated by Django 5.2.3 on 2026-01-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_interaction_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='template',
            field=models.CharField(choices=[('template1', 'Modèle 1 (Classique)'), ('template2', 'Modèle 2 (Moderne)'), ('template3', 'Modèle 3 (Élégant)')], default='template1', max_length=20, verbose_name='Modèle de badge'),
        ),
    ]
